config/routes.rb
VirtualGym::Application.routes.draw do

  get "/profiles/add_friend"
  get "/profiles/index_friend"

  get "/messages/inbox"
  get "/messages/sent"

    authenticated :user do
      resources :profiles
    end
    unauthenticated :user do
      root :to => redirect("users/sign_up")
    end

  resources :workout_plans do
    member do
      get :add_exercise
    end
    member do
      post :sort
    end
  end

  resources :exercises do
    collection do
      get :add_exercise
    end
  end

  resources :workout_includings do
    member do
      post :set_fields
    end
  end

  devise_for :users

  resources :messages

  resources :friendships

  resources :amount_types

  resources :equipment

  resources :foods

  resource :users

  resources :exercises

  resources :workouts

  resources :plans

end

app/models/amount_type.rb
class AmountType < ActiveRecord::Base
  has_many :foods
  validates_presence_of :name
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :equipment
  has_many :workout_includings
  has_many :workout_plans, :through => :workout_includings


  mount_uploader :video, VideoUploader
  has_attached_file :avatar, :styles => { :medium => "200x200#", :thumb => "100x100#" }, :default_url => "/images/:style/exer.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :amount_type
  has_attached_file :avatar, :styles => { :medium => "200x200#", :thumb => "50x50#" }, :default_url => "/images/:style/Fruit.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
    if search
      where( 'name LIKE ?  ', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from , class_name: "User"
  belongs_to :to , class_name: "User"

  def self.read_message(message,current_user)
    if current_user == message.to_id
      message.status = 1
      message.save
    end
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_and_belongs_to_many :foods
  has_many :taking_food_plans
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_one :user
  
  has_attached_file :avatar, :styles => { :medium => "200x200#", :thumb => "100x100#" }, :default_url => "/images/:style/profile.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_attached_file :cover, :styles => { :medium => "1100x472#", :thumb => "100x100#" }, :default_url => "/images/:style/cover.jpg"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :firstname , :lastname , :birthdate , :height , :weight , :country , :city
  validates_numericality_of :height
  def self.search(search)
    if search
      where( 'firstname LIKE ? OR lastname LIKE ? ', "%#{search}%","%#{search}%")
    else
      scoped
    end
  end

  def self.search_friend(search)
    if ! search.blank?
      where( 'firstname LIKE ? OR lastname LIKE ? ', "%#{search}%","%#{search}%")
    else
      where(' 1=0')
    end
  end



end

app/models/taking_food_plan.rb
class TakingFoodPlan < ActiveRecord::Base
  belongs_to :profile
  belongs_to :plan

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :profile
  has_many :workouts
  has_many :taking_food_plans

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friend ,:through => :friendships
  has_many :inbox_message , :class_name => 'Message' , :foreign_key => 'to_id'
  has_many :sent_message , :class_name => 'Message' , :foreign_key => 'from_id'
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout_plan
end

app/models/workout_including.rb
class WorkoutIncluding < ActiveRecord::Base
  belongs_to :workout_plan
  belongs_to :exercise
end

app/models/workout_plan.rb
class WorkoutPlan < ActiveRecord::Base
  has_many :workout_includings
  has_many :exercises, :through => :workout_includings
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  layout "admin"
  # GET /profiles
  # GET /profiles.json
  def index
    @search_box = Profile.search_friend(params[:search]).paginate(:page => params[:page], :per_page => 5)
    @profiles = Profile.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @message = Message.new
    conditions = { user_id: current_user.id,
                   friend_id: @profile.user.id }
    @friendship = Friendship.find(:first , :conditions => conditions)
    @inbox = current_user.inbox_message.where('status = 0').count
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
      current_user.profile = @profile
      current_user.save

    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    @profile.user.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
  def add_friend
    @profiles = Profile.search_friend(params[:search]).paginate(:page => params[:page], :per_page => 10)
    @friendships = current_user.friendships.paginate(:page => params[:friended_page], :per_page => 10)
  end

  def index_friend
    @friendships = current_user.friendships.paginate(:page => params[:page], :per_page => 5)
    @count = current_user.friendships.count
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :birthdate, :height, :weight, :country, :city, :role,:avatar,:cover ,:language)
    end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4><strong>#{sentence}</strong></h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def age(birthday)
    now = Time.now.utc.to_date
    now.year - birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile, :html => { :multipart => true }) do |f| %>
    <% if @profile.errors.any? %>
        <div class="alert alert-danger">
          <h3><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h3>

          <ul>
            <% @profile.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.firstname') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <%= f.text_field :firstname ,:class => 'form-control ', :placeholder => 'Firstname'%>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.lastname') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <%= f.text_field :lastname ,:class => 'form-control ', :placeholder => 'Lastname'%>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.profpic') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <%= f.file_field :avatar %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.coverpic') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <%= f.file_field :cover %>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-7 col-sm-7 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.birthdate') ,:class => "col-sm-3 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-9 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <%= f.date_select :birthdate, {:prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' },:start_year => Time.now.year-70, :end_year => Time.now.year}, {:class => 'date-select'}  %>
          </div>
        </div>
      </div>
    </div>

    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.height') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <div class="input-group">
              <%= f.text_field :height,:class => 'form-control ', :placeholder => 'Height (cm)'%>
              <span class="input-group-addon">cm</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.weight') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <div class="input-group">
              <%= f.text_field :weight ,:class => 'form-control ', :placeholder => 'Weight (kg)'%>
              <span class="input-group-addon">kg</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.country') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8">
            <%= f.text_field :country ,:class => 'form-control ', :placeholder => 'Country'%>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.city'),:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <%= f.text_field :city ,:class => 'form-control ', :placeholder => 'City'%>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
        <div class="form-group">
          <%= f.label t('activemodel.activerecord.attributes.profile.language') ,:class => "col-sm-4 control-label #{t('activemodel.activerecord.attributes.profile.pull').html_safe}"%>
          <div class="col-sm-8 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
            <%= f.select :language , [['English','en'],['فارسی','fa']] ,{}, {:class => 'form-control' } %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <!--<button type="submit" class="btn btn-primary"> Let's Go <span class="glyphicon glyphicon-chevron-right"></span></button>-->

        <%= f.submit  :class => 'btn btn-info'  %>

    </div>
<% end %>

app/views/profiles/_friended.html.erb
<div class="table-responsive" >
  <table class="table">
    <tbody>
    <% @friendships.each do |friendship| %>
        <tr>
          <td><%=image_tag friendship.friend.profile.avatar.url(:thumb) ,{id: friendship.friend.profile.id , class: "img-circle img-responsive img-thumbnail" , width: "100" , height: "100" , alt: "Profile"}%>
          <td><%= link_to highlight(friendship.friend.profile.firstname+" "+friendship.friend.profile.lastname+" ("+friendship.friend.email+")" ,friendship.friend.profile.firstname+" "+friendship.friend.profile.lastname,:highlighter => '<strong>\1</strong>') ,friendship.friend.profile , class: "btn btn-link" %> </td>
          <td></td>
          <td></td>
          <td></td>
          <td><%=link_to raw('<h3><span class="glyphicon glyphicon-minus"></span></h3>'), friendship, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"%>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @friendships , renderer: BootstrapPagination::Rails %>

app/views/profiles/_friends.html.erb
<div class="table-responsive" >
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Friend</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @profiles.each do |profile| %>
    <%  if (!current_user.friends.include? profile.user) && current_user != profile.user %>
        <tr>
          <td><%=image_tag profile.avatar.url(:thumb) ,{id: profile.id , class: "img-circle img-responsive img-thumbnail" , width: "100" , height: "100" , alt: "Profile"}%>
          <td><%= link_to highlight(profile.firstname+" "+profile.lastname+" ("+profile.user.email+")" ,profile.firstname+" "+profile.lastname,:highlighter => '<strong>\1</strong>') , profile  , class: "btn btn-link"%> </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><%=link_to raw('<h3><span class="glyphicon glyphicon-plus"></span></h3>'),  friendships_path(:friend_id => profile.user) , method: :post , class: "btn btn-link"%>
          </td>
        </tr>
    <% end  %>
    <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @profiles, renderer: BootstrapPagination::Rails %>

app/views/profiles/_profileButtons.html.erb
<div class="btn-group btn-group-lg pull-right">
  <% unless @iscreate  %>
      <%=link_to raw('<i class="fa fa-user"></i> Friend Request'), friendships_path(:friend_id => @profile.user,profile_id: @profile),remote: true , method: :post , class: 'btn btn-primary'%>
  <% else %>
      <%=link_to raw('<i class="fa fa-user"></i> Remove'), @friendship, method: :delete, data: { confirm: 'Are you sure?' },remote: true,  class: 'btn btn-primary'%>
  <% end %>

  <a  data-toggle="modal" data-target="#pm" class="btn btn-info">
    <i class="fa fa-comment-o"></i>
  </a>
</div>

app/views/profiles/_profiles.html.erb
  <div class="table-responsive" >
    <table class="table table-hover" >
      <thead>
      <tr>
        <th>Profile Picture</th>
        <th>Username</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Birthdate</th>
        <th>Country</th>
        <th>City</th>
        <th><%= t('activemodel.activerecord.attributes.profile.role') %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @profiles.each do |profile| %>
          <tr>
            <td><%= image_tag profile.avatar.url(:thumb) ,{id: profile.id , class: "img-circle img-responsive img-thumbnail" , width: "100" , height: "100" , alt: "Profile"}%>
            <td><%= profile.user.email %></td>
            <td><%= profile.firstname %></td>
            <td><%= profile.lastname %></td>
            <td><%= profile.birthdate %></td>
            <td><%= profile.country.capitalize %></td>
            <td><%= profile.city.capitalize %></td>
            <td></td>
            <td><%= link_to raw('<span class="glyphicon glyphicon-list-alt"></span> Show'), profile %></td>
            <td><%= link_to raw('<span class="glyphicon glyphicon-pencil"></span> Edit'), edit_profile_path(profile) %></td>
            <td><%= link_to raw('<span class="glyphicon glyphicon-remove"></span> Remove'), profile, method: :delete, data: { confirm: "#{t('activemodel.activerecord.attributes.profile.removequest')}" } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @profiles, renderer: BootstrapPagination::Rails %>

app/views/profiles/_search_result.html.erb
<% @search_box.each do |profile| %>
    <li ><%= link_to raw("#{profile.firstname} #{profile.lastname}<br /><span>#{profile.user.email}</span>"),profile ,style: 'color: #808394'%></li>
<% end %>
<li><%= link_to raw("More Result <br /><span>Profiles</span>"),profiles_path ,style: 'color: #808394'%></li>

app/views/profiles/add_friend.html.erb
<ul class="nav nav-pills nav-justified ">

  <li><%= link_to  "Home" , action: "show", id: current_user.profile_id %></li>
  <li><a href="workout.html">Workouts</a></li>
  <li><a href="#">Challenges</a></li>
  <li><a href="#">Chart</a></li>
  <li><a href="#">Nutrition (PRO)</a></li>
  <li class="active"><%= link_to  "Friends" , profiles_add_friend_path %></li>

</ul>
<br>
<br>
<p id="notice"><%= notice %></p>
<h1>Search Friends </h1>
<br>

<%= javascript_include_tag "partial/add_friend_ajax" %>


<%= form_tag({controller: "profiles", action: "add_friend"}, method: "get", class: "form-inline" , id: "friend_search") do %>
    <p>
    <div class="form-group">
      <%= text_field_tag :search, params[:search] ,:class => 'form-control ' ,:placeholder => "Enter User"%>
    </div>
    <div class="form-group">
      <%= submit_tag "Search",:class => 'btn btn-primary ', :name => nil %>
    </div>
    </p>
<% end %>

<br>
<br>
<div id="friend">
  <%= render partial: 'friends' %>
</div>
<br>

<h1>Friends </h1>
<br>
<div id="friended">
  <%= render partial: 'friended' %>
</div>

app/views/profiles/add_friend.js.erb
$("#friend").html("<%= escape_javascript(render partial: 'friends') %>");
$("#friended").html("<%= escape_javascript(render partial: 'friended') %>");

app/views/profiles/edit.html.erb
<h1><%= t('profile.editprofile') %></h1>

<%= render 'form' ,locals: {:is_edit => true}%>

app/views/profiles/index.html.erb
<h1><%= I18n.t('activemodel.activerecord.attributes.profile.listprof') %></h1>
<br>
<%= javascript_include_tag "partial/pagination" %>
<%= form_tag profiles_path, :method => 'get' , :class => 'form-inline',:id => 'profile_search' do %>
    <p>
    <div class="form-group">
      <%= text_field_tag :search, params[:search] ,:class => 'form-control ' ,:placeholder => t('activemodel.activerecord.attributes.profile.enterplace')%>
    </div>
    <div class="form-group">
      <%= submit_tag t('activemodel.activerecord.attributes.profile.search'),:class => 'btn btn-primary ', :name => nil %>
    </div>
    </p>
<% end %>

<br>
<br>
<div id="profile">
    <%= render 'profiles' %>
 </div>

app/views/profiles/index.js.erb
$('#results').html("<%=  escape_javascript(render ('search_result'))%>");
$("#profile").html("<%= escape_javascript(render('profiles')) %>");

app/views/profiles/index_friend.js.erb
$('#friendModal').modal('show');
$('#modalFriendDiv').html("<%= escape_javascript(render 'friended') %>");
$('#FriendModalLabel').html("<strong>Friends</strong> (<%= @count %>)");

app/views/profiles/new.html.erb
<h1>New Profile</h1>



<%= render 'form' , locals: {:is_edit => false}%>

app/views/profiles/show.html.erb
    <div id="alert">

    </div>



    <%= image_tag @profile.cover.url(:medium),{alt: "Cover" , width: "100%" , height: "472" , class: "img-responsive" , id: "mainCover"} %>

  <div class="row">
    <div class="col-md-offset-1 col-md-3 col-sm-offset-1 col-sm-3 col-xs-offset-1 col-xs-3 <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
      <%= image_tag @profile.avatar.url(:medium) ,{id:"profilePic" , class: "img-circle img-responsive img-thumbnail" , width: "200" , height: "200" , alt: "Profile"}%>
    </div>
    <div class="col-md-3 col-sm-3  col-xs-12 infoDiv <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
      <h3> <%= "#{@profile.firstname} #{@profile.lastname}" %> </h3>
      <ul>
        <li><span class="glyphicon glyphicon-star">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.age').html_safe %>: <%= age(@profile.birthdate) %></li>
        <li><span class="glyphicon glyphicon-star">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.height').html_safe %>: <%= @profile.height %> cm</li>
        <li><span class="glyphicon glyphicon-star">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.weight').html_safe %>: <%= @profile.weight %> kg</li>
        <li><span class="glyphicon glyphicon-star">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.country').html_safe %>: <%= @profile.country.capitalize %></li>
        <li><span class="glyphicon glyphicon-star">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.city').html_safe %>: <%= @profile.city.capitalize %></li>
      </ul>
    </div>
    <div class="col-md-offset-1 col-md-3  col-sm-4 col-xs-12 infoDiv <%= t('activemodel.activerecord.attributes.profile.pull').html_safe %>">
      <h3>Total</h3>
      <ul>
        <li><span class="glyphicon glyphicon-fire">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.totalcal').html_safe %>: 12,360</li>
        <li><span class="glyphicon glyphicon-dashboard">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.totalTime').html_safe %>: 3:30:32</li>
        <li><span class="glyphicon glyphicon-stats">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.level').html_safe %>: easy</li>
        <li><span class="glyphicon glyphicon-road">  </span> <%= label_tag t('activemodel.activerecord.attributes.profile.totalDistance').html_safe %>: 2.21 km</li>
      </ul>
    </div>
  </div>

    <div class="row" id="profileButtons">
      <% unless current_user.profile_id == @profile.id %>

          <div class="btn-group btn-group-lg pull-right">
            <% unless (current_user.friends.include? @profile.user) %>
                <%=link_to raw('<i class="fa fa-user"></i> Friend Request'), friendships_path(:friend_id => @profile.user,profile_id: @profile),remote: true , method: :post , class: 'btn btn-primary'%>
            <% else %>
                <%=link_to raw('<i class="fa fa-user"></i> Remove'), @friendship, method: :delete, data: { confirm: 'Are you sure?' },remote: true,  class: 'btn btn-primary'%>
                <!-- <li ><%= link_to 'Private Messages' , new_message_path(to: @profile.user.id) %></li> -->

            <% end %>
            <a  data-toggle="modal" data-target="#pm" class="btn btn-info">
              <i class="fa fa-comment-o"></i>
            </a>
          </div>


      <% end%>

    </div>