config/routes.rb
VirtualGym::Application.routes.draw do

  get "/profiles/add_friend"
  get "/profiles/index_friend"

  get "/messages/inbox"
  get "/messages/sent"

    authenticated :user do
      resources :profiles
    end
    unauthenticated :user do
      root :to => redirect("users/sign_up")
    end

  resources :workout_plans do
    member do
      get :add_exercise
    end
    member do
      post :sort
    end
  end

  resources :exercises do
    collection do
      get :add_exercise
    end
  end

  resources :workout_includings do
    member do
      post :set_fields
    end
  end

  devise_for :users

  resources :messages

  resources :friendships

  resources :amount_types

  resources :equipment

  resources :foods

  resource :users

  resources :exercises

  resources :workouts

  resources :plans

end

app/models/amount_type.rb
class AmountType < ActiveRecord::Base
  has_many :foods
  validates_presence_of :name
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :equipment
  has_many :workout_includings
  has_many :workout_plans, :through => :workout_includings


  mount_uploader :video, VideoUploader
  has_attached_file :avatar, :styles => { :medium => "200x200#", :thumb => "100x100#" }, :default_url => "/images/:style/exer.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :amount_type
  has_attached_file :avatar, :styles => { :medium => "200x200#", :thumb => "50x50#" }, :default_url => "/images/:style/Fruit.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
    if search
      where( 'name LIKE ?  ', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from , class_name: "User"
  belongs_to :to , class_name: "User"

  def self.read_message(message,current_user)
    if current_user == message.to_id
      message.status = 1
      message.save
    end
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_and_belongs_to_many :foods
  has_many :taking_food_plans
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_one :user
  
  has_attached_file :avatar, :styles => { :medium => "200x200#", :thumb => "100x100#" }, :default_url => "/images/:style/profile.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_attached_file :cover, :styles => { :medium => "1100x472#", :thumb => "100x100#" }, :default_url => "/images/:style/cover.jpg"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :firstname , :lastname , :birthdate , :height , :weight , :country , :city
  validates_numericality_of :height
  def self.search(search)
    if search
      where( 'firstname LIKE ? OR lastname LIKE ? ', "%#{search}%","%#{search}%")
    else
      scoped
    end
  end

  def self.search_friend(search)
    if ! search.blank?
      where( 'firstname LIKE ? OR lastname LIKE ? ', "%#{search}%","%#{search}%")
    else
      where(' 1=0')
    end
  end



end

app/models/taking_food_plan.rb
class TakingFoodPlan < ActiveRecord::Base
  belongs_to :profile
  belongs_to :plan

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :profile
  has_many :workouts
  has_many :taking_food_plans

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friend ,:through => :friendships
  has_many :inbox_message , :class_name => 'Message' , :foreign_key => 'to_id'
  has_many :sent_message , :class_name => 'Message' , :foreign_key => 'from_id'
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout_plan
end

app/models/workout_plan.rb
class WorkoutPlan < ActiveRecord::Base
  has_many :workout_includings
  has_many :exercises, :through => :workout_includings
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all.order(:part).order(:level).paginate(:page => params[:page], :per_page => 3)
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show

  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
    @equipments = Equipment.order('name ASC')
  end

  # GET /exercises/1/edit
  def edit
    @equipments = Equipment.order('name ASC')
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render action: 'show', status: :created, location: @exercise }
      else
        @equipments = Equipment.order('name ASC')
        format.html { render action: 'new' }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { head :no_content }
      else
        @equipments = Equipment.order('name ASC')
        format.html { render action: 'edit' }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end


  def add_exercise
    @exercises = Exercise.search(params[:search])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exercise_params
    params.require(:exercise).permit(:name, :part, :description, :description_fa, :level, :equipment_id, :days_per_week , :video, :avatar)
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4><strong>#{sentence}</strong></h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def age(birthday)
    now = Time.now.utc.to_date
    now.year - birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> Add Exercise </h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :name ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.text_field :name ,:class => 'form-control ', :placeholder => 'name'%>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :part ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.select :part, ['ABS' , 'Chest' , 'Back' , 'Legs' , 'Arms'] ,{}, {:class => 'form-control'}%>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label  :days_per_week ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-7">
            <%= f.number_field :days_per_week ,:class => 'form-control '%>
          </div>
        </div>
      </div>
    </div>

    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :level ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
              <%= f.select :level, ['Basic'=> '0' ,'Intermediate'=> '1' , 'Difficult' => '2'] ,{}, {:class => 'form-control'}%>
            </div>
          </div>
        </div>
      </div>


    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :equipment ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.select :equipment_id, @equipments.map { |e| [ e.name , e.id ] } ,{}, {:class => 'form-control' } %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :description ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.text_area :description ,:class => 'form-control ',size: "24x6", :placeholder => 'description' %>
          </div>
         </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :description_fa ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.text_area :description_fa ,:class => 'form-control ',size: "24x6", :placeholder => 'description_fa'%>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :link ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.file_field :video %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label :avatar ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.file_field :avatar %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="actions">
      <%= f.submit :class => 'btn btn-primary'%>
    </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Edit Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Exercises </h1><br>
<%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_exercise_path ,:class => "btn btn-primary" , :style => "color: rgb(255,255,255);"%><br><br>
<br>
<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Avatar</th>
      <th><strong>Part</strong></th>
      <th>Name</th>
      <th>Level</th>
      <th>Equipment</th>
      <th>Days per week</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= image_tag exercise.avatar.url(:thumb) ,{id: exercise.id , class: "img-circle img-responsive img-thumbnail" , width: "100" , height: "100" , alt: "Exercise"}%>
        <td><strong><%= exercise.part %></strong></td>
        <td><%= exercise.name.capitalize %></td>
        <td>
            <% case exercise.level %>
                <% when 0%>
            <%= 'Basic' %>
                <% when 1%>
            <%= 'Intermediate' %>
                <% when 2%>
            <%= 'Difficult' %>
            <% end%>
        </td>
        <td><%= exercise.equipment.name.capitalize %></td>
        <td><%= exercise.days_per_week %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-list-alt"></span> Show'), exercise %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-pencil"></span> Edit'), edit_exercise_path(exercise) %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-remove"></span> Destroy'), exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>

<br>
<%= will_paginate @exercises, renderer: BootstrapPagination::Rails %>

app/views/exercises/new.html.erb
<h1>Add Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<ul class="nav nav-pills nav-justified ">

  <li><%=  link_to "Home", controller: "profiles", action: "show", id: current_user.profile_id %></li>
  <li><a href="#">Workouts</a></li>
  <li><a href="#">Challenges</a></li>
  <li><a href="#">Chart</a></li>
  <li><a href="#">Nutrition (PRO)</a></li>

</ul>
<br>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
    <br>
  <% end %>

<div class="row">
  <div class="col-md-8  col-sm-8  col-xs-12">


        <%= videojs_rails id:"example_video_1" ,  sources: { mp4: @exercise.video_url}  %>

  </div>
  <div class="col-md-4 col-sm-4 col-xs-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>Name:</strong><%= @exercise.name %></h3>
      </div>
      <div class="panel-body">
        <p>
          <strong>Type:</strong>
          <%= @exercise.part %>
        </p>

        <p>
          <strong>Description English:</strong>
          <%= @exercise.description %>
        </p>

        <p>
          <strong>Description Farsi:</strong>
          <%= @exercise.description_fa %>
        </p>

        <p>
          <strong>Level:</strong>
          <% case @exercise.level %>
          <% when 0%>
              <%= "Basic" %>
          <% when 1%>
              <%= "Intermediate" %>
          <% when 2%>
              <%= "Difficult" %>
          <% end%>
        </p>

        <p>
          <strong>Equipment:</strong>
          <%= @exercise.equipment.name %>
        </p>

        <p>
          <strong>Days per week:</strong>
          <%= @exercise.days_per_week %>
        </p>
      </div>



    </div>
  </div>
</div>
  <br>
  <div class="row">

  </div>


<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>